kind: source
spec:
  name: "productboard"
  registry: "grpc"
  path: "localhost:7777"
  tables: ["pb_notes"]
  destinations: ["sqlite"]
  spec:
    api_token: "${PB_API_KEY}"
---
kind: destination
spec:
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.4.11"
  spec:
    connection_string: ./db.sqlite
