kind: source
spec:
  name: "productboard"
  registry: "grpc"
  path: "localhost:7777"
  tables:
    - pb_companies
    - pb_notes
    - pb_users
    - pb_features
    - pb_components
    - pb_products
  destinations: ["sqlite"]
  spec:
    api_token: "${PB_API_KEY}"
---
kind: destination
spec:
  send_sync_summary: true
  name: sqlite
  path: cloudquery/sqlite
  version: "v2.13.1"
  spec:
    connection_string: ./db.sqlite
